---
title: "ANPP_Figs"
author: "Alex Siggers"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(lattice);library(doBy); library(lubridate)
library(minpack.lm); library(effects); library(nlme)
library(MuMIn); library(car)
library(sjPlot)
library(lattice);library(doBy); library(lubridate)
library(minpack.lm); library(plotrix); library(multcomp); library(emmeans)

```

#Data Read & Formatting
```{r}
setwd("C:\\Users\\jasig\\OneDrive - Colostate\\Documents\\My Projects\\BADDIE")
ANPP=read.csv("JSG 2023 6ft ANPP.csv")
ANPP$Microsite[ANPP$Microsite == "U"] = "Beneath"
ANPP$Microsite[ANPP$Microsite == "E"] = "East"
ANPP$Microsite[ANPP$Microsite == "W"] = "West"
ANPP$Microsite[ANPP$Microsite == "BW"] = "Between"
ANPP$Microsite[ANPP$Microsite == "CTRL"] = "Control"
ANPP$Microsite=as.factor(ANPP$Microsite)
ANPP$Treatment=as.factor(ANPP$Treatment)


m1<-lm(ANPP~Microsite, ANPP)
anova(m1)
summary(m1)
plot(allEffects(m1))
d1=cld(emmeans(m1, ~ Microsite))

C<-subset(d1, Microsite == "Control")
E<-subset(d1, Microsite == "East")
W<-subset(d1, Microsite == "West")
Ben<-subset(d1, Microsite == "Beneath")
Bet<-subset(d1, Microsite == "Between")
```

#Creating Figure
```{r}
tiff(file = "BADDIE ANPP Microsite w bar.tiff", height = 8, width = 8, res = 400, units = "in", compression = "zip+p")
par(mfrow = c(1,1), omi = c(0.8, 1, 0.4, 0.1), mar = c(1.5,2.5,0.5,0.5))

xx<-c(-500,500); yy<-c(-500,500)

plot(yy ~ xx, pch = NA, xlab="",ylab="",xaxt="n",yaxt="n",ylim=c(100,900), xlim=c(6,40))

rect(xleft = -2, xright = 102, ybottom = 526, ytop = 634, col = "lightcyan2", bty = "n", border = F)
ablineclip(h=580,lwd = 5, lty =2, col = "black")

rect(xleft = 22.5, xright = 23.5, ybottom = -200, ytop = 800, col = "grey52", bty = "n", border = F)
rect(xleft = 22.95, xright = 23.05, ybottom = -200, ytop = 800, col = "grey52", bty = "n", border = F)
rect(xleft = 16, xright = 30, ybottom = 785, ytop = 800, col = "grey52", bty = "n", border = F)
rect(xleft = 16, xright = 30, ybottom = 795, ytop = 798, col = "black", bty = "n", border = F)


dum<-subset(d1, Microsite == "Between")
rect(34, 00, 38, mean(dum$emmean), col = "grey69", border = "grey69")
ablineclip(v=36, y1=as.numeric(mean(dum$emmean) + (dum$SE)), y2=as.numeric(mean(dum$emmean) - (dum$SE)),lwd = 2, col = "gray2")

dum<-subset(d1, Microsite == "East")
rect(28, 00, 32, mean(dum$emmean), col = "cornflowerblue", border = "cornflowerblue")
ablineclip(v=30, y1=as.numeric(mean(dum$emmean) + (dum$SE)), y2=as.numeric(mean(dum$emmean) - (dum$SE)),lwd = 2, col = "gray2")

dum<-subset(d1, Microsite == "Beneath")
rect(21, 00, 25, mean(dum$emmean), col = "aquamarine3", border = "aquamarine3")
ablineclip(v=23, y1=as.numeric(mean(dum$emmean) + (dum$SE)), y2=as.numeric(mean(dum$emmean) - (dum$SE)),lwd = 2, col = "gray2")

dum<-subset(d1, Microsite == "West")
rect(14, 00, 18, mean(dum$emmean), col = "indianred4", border = "indianred4")
ablineclip(v=16, y1=as.numeric(mean(dum$emmean) + (dum$SE)), y2=as.numeric(mean(dum$emmean) - (dum$SE)),lwd = 2, col = "gray2")

dum<-subset(d1, Microsite == "Between")
rect(08, 00, 12, mean(dum$emmean), col = "grey69", border = "grey69")
ablineclip(v=10, y1=as.numeric(mean(dum$emmean) + (dum$SE)), y2=as.numeric(mean(dum$emmean) - (dum$SE)),lwd = 2, col = "gray2")

text(23, 320, expression('b'),cex=2)
text(36, 615, expression('a'),cex=2)
text(10, 615, expression('a'),cex=2)
text(16, 620, expression('a'),cex=2)
text(30, 710, expression('a'),cex=2)

box()

text(23, 810, expression('Solar Panel'),cex=0.8)

axis(2, cex.axis = 2, labels = T)
mtext(side = 2, expression(ANPP~(g~m^-2)), cex = 3, padj = -1, outer= F)
mtext(side = 1, expression(Plot), cex = 3, padj = 1, outer= F)

legend("topleft", c(expression(W [edge]),"Beneath" , expression(E [edge]), "Between" ), col=c("indianred4", "aquamarine3", "cornflowerblue", "grey69"), bty = "n", pch = 15,cex = 1.2)
legend("topright", c("Control"), col=c("black"), bty = "n", lty = 2, lwd = 3,cex = 1.2)

dev.off()
```

